# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
  - recent_posts
  - category
  - tagcloud

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-70668709-6
favicon: /favicon.png
twitter: https://twitter.com/esrhim
google_plus: https://plus.google.com/u/0/113537401711657998977?rel=author
fb_admins:
fb_app_id:
